name: decision_tree
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - scikit-learn=1.0.2
  - matplotlib=3.2.2
  - pillow=8.4.0
  - mlflow=1.14.1
  - pip:
      - wandb==0.12.9
      - mlflow==1.14.1
      - omegaconf==2.1.1